# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBIx-MyServer
version:      0.20
version_from: lib/DBIx/MyServer.pm
installdirs:  site
requires:
    Digest::SHA1:                  2.11

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
